name: flutters
description: A flutter game that teaches how to flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flame: ^0.11.1
  url_launcher: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf
  assets:
    - assets/audio/bgm/fluttery-meadow.ogg
    - assets/audio/sfx/bump1.ogg
    - assets/audio/sfx/bump2.ogg
    - assets/audio/sfx/bump3.ogg
    - assets/images/bird-0.png
    - assets/images/bird-1.png
    - assets/images/bird-0-left.png
    - assets/images/bird-1-left.png
    - assets/images/cloud-1.png
    - assets/images/cloud-2.png
    - assets/images/cloud-3.png

  uses-material-design: true
